//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargaAspNew.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/kayitol", ReplyAction="http://tempuri.org/IService1/kayitolResponse")]
        string kayitol(string ad, string soyad, string sifre, string sifretekrar, long tel, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/kayitol", ReplyAction="http://tempuri.org/IService1/kayitolResponse")]
        System.Threading.Tasks.Task<string> kayitolAsync(string ad, string soyad, string sifre, string sifretekrar, long tel, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/giris", ReplyAction="http://tempuri.org/IService1/girisResponse")]
        string giris(string email, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/giris", ReplyAction="http://tempuri.org/IService1/girisResponse")]
        System.Threading.Tasks.Task<string> girisAsync(string email, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guvenlikkodugndr", ReplyAction="http://tempuri.org/IService1/guvenlikkodugndrResponse")]
        int guvenlikkodugndr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/guvenlikkodugndr", ReplyAction="http://tempuri.org/IService1/guvenlikkodugndrResponse")]
        System.Threading.Tasks.Task<int> guvenlikkodugndrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iletisimformual", ReplyAction="http://tempuri.org/IService1/iletisimformualResponse")]
        void iletisimformual(string adsoyad, string email, long tel, string konu, string mesaj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iletisimformual", ReplyAction="http://tempuri.org/IService1/iletisimformualResponse")]
        System.Threading.Tasks.Task iletisimformualAsync(string adsoyad, string email, long tel, string konu, string mesaj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sifremiunuttum", ReplyAction="http://tempuri.org/IService1/sifremiunuttumResponse")]
        string sifremiunuttum(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sifremiunuttum", ReplyAction="http://tempuri.org/IService1/sifremiunuttumResponse")]
        System.Threading.Tasks.Task<string> sifremiunuttumAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bilgigetir", ReplyAction="http://tempuri.org/IService1/bilgigetirResponse")]
        KargaAspNew.ServiceReference1.bilgigetirResponse bilgigetir(KargaAspNew.ServiceReference1.bilgigetirRequest request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti sözleşmesi oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bilgigetir", ReplyAction="http://tempuri.org/IService1/bilgigetirResponse")]
        System.Threading.Tasks.Task<KargaAspNew.ServiceReference1.bilgigetirResponse> bilgigetirAsync(KargaAspNew.ServiceReference1.bilgigetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/tcnoctrl", ReplyAction="http://tempuri.org/IService1/tcnoctrlResponse")]
        string tcnoctrl(string tcno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/tcnoctrl", ReplyAction="http://tempuri.org/IService1/tcnoctrlResponse")]
        System.Threading.Tasks.Task<string> tcnoctrlAsync(string tcno);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bilgigetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class bilgigetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string soyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public long tel;
        
        public bilgigetirRequest() {
        }
        
        public bilgigetirRequest(string email, string ad, string soyad, string sifre, long tel) {
            this.email = email;
            this.ad = ad;
            this.soyad = soyad;
            this.sifre = sifre;
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bilgigetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class bilgigetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string soyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long tel;
        
        public bilgigetirResponse() {
        }
        
        public bilgigetirResponse(string ad, string soyad, string sifre, long tel) {
            this.ad = ad;
            this.soyad = soyad;
            this.sifre = sifre;
            this.tel = tel;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : KargaAspNew.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<KargaAspNew.ServiceReference1.IService1>, KargaAspNew.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string kayitol(string ad, string soyad, string sifre, string sifretekrar, long tel, string email) {
            return base.Channel.kayitol(ad, soyad, sifre, sifretekrar, tel, email);
        }
        
        public System.Threading.Tasks.Task<string> kayitolAsync(string ad, string soyad, string sifre, string sifretekrar, long tel, string email) {
            return base.Channel.kayitolAsync(ad, soyad, sifre, sifretekrar, tel, email);
        }
        
        public string giris(string email, string sifre) {
            return base.Channel.giris(email, sifre);
        }
        
        public System.Threading.Tasks.Task<string> girisAsync(string email, string sifre) {
            return base.Channel.girisAsync(email, sifre);
        }
        
        public int guvenlikkodugndr() {
            return base.Channel.guvenlikkodugndr();
        }
        
        public System.Threading.Tasks.Task<int> guvenlikkodugndrAsync() {
            return base.Channel.guvenlikkodugndrAsync();
        }
        
        public void iletisimformual(string adsoyad, string email, long tel, string konu, string mesaj) {
            base.Channel.iletisimformual(adsoyad, email, tel, konu, mesaj);
        }
        
        public System.Threading.Tasks.Task iletisimformualAsync(string adsoyad, string email, long tel, string konu, string mesaj) {
            return base.Channel.iletisimformualAsync(adsoyad, email, tel, konu, mesaj);
        }
        
        public string sifremiunuttum(string email) {
            return base.Channel.sifremiunuttum(email);
        }
        
        public System.Threading.Tasks.Task<string> sifremiunuttumAsync(string email) {
            return base.Channel.sifremiunuttumAsync(email);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KargaAspNew.ServiceReference1.bilgigetirResponse KargaAspNew.ServiceReference1.IService1.bilgigetir(KargaAspNew.ServiceReference1.bilgigetirRequest request) {
            return base.Channel.bilgigetir(request);
        }
        
        public void bilgigetir(string email, ref string ad, ref string soyad, ref string sifre, ref long tel) {
            KargaAspNew.ServiceReference1.bilgigetirRequest inValue = new KargaAspNew.ServiceReference1.bilgigetirRequest();
            inValue.email = email;
            inValue.ad = ad;
            inValue.soyad = soyad;
            inValue.sifre = sifre;
            inValue.tel = tel;
            KargaAspNew.ServiceReference1.bilgigetirResponse retVal = ((KargaAspNew.ServiceReference1.IService1)(this)).bilgigetir(inValue);
            ad = retVal.ad;
            soyad = retVal.soyad;
            sifre = retVal.sifre;
            tel = retVal.tel;
        }
        
        public System.Threading.Tasks.Task<KargaAspNew.ServiceReference1.bilgigetirResponse> bilgigetirAsync(KargaAspNew.ServiceReference1.bilgigetirRequest request) {
            return base.Channel.bilgigetirAsync(request);
        }
        
        public string tcnoctrl(string tcno) {
            return base.Channel.tcnoctrl(tcno);
        }
        
        public System.Threading.Tasks.Task<string> tcnoctrlAsync(string tcno) {
            return base.Channel.tcnoctrlAsync(tcno);
        }
    }
}
